_target_: lightning.Trainer
accelerator:
  _target_: lightning_habana.pytorch.accelerator.HPUAccelerator
callbacks:
  - ${callbacks.best_checkpoint_callback}
  - ${callbacks.last_checkpoint_callback}
  - ${callbacks.exception_checkpoint_callback}
detect_anomaly: false
devices: 1
limit_train_batches: 100
limit_val_batches: 0
log_every_n_steps: 100
logger: ${logger}
max_epochs: 2
num_sanity_val_steps: 1
precision: bf16-mixed
profiler:
  _target_: lightning_habana.pytorch.profiler.profiler.HPUProfiler
reload_dataloaders_every_n_epochs: 1
strategy:
  _target_: lightning_habana.pytorch.strategies.SingleHPUStrategy
val_check_interval: 100
