_target_: lightning.Trainer
accelerator:
  _target_: lightning_habana.pytorch.accelerator.HPUAccelerator
detect_anomaly: false
devices: 1
enable_checkpointing: false
limit_train_batches: 20
limit_val_batches: 0
log_every_n_steps: 20
logger: ${logger}
max_epochs: 1
num_sanity_val_steps: 0
precision: bf16-mixed
profiler: "simple"
strategy:
  _target_: lightning_habana.pytorch.strategies.SingleHPUStrategy
val_check_interval: 20
