_target_: lightning.Trainer
accelerator:
  _target_: lightning_habana.pytorch.accelerator.HPUAccelerator
check_val_every_n_epoch: null
detect_anomaly: false
devices: 1
enable_checkpointing: false
log_every_n_steps: 10
logger: ${logger}
max_epochs: 99999
overfit_batches: 1
precision: bf16-mixed
strategy:
  _target_: lightning_habana.pytorch.strategies.SingleHPUStrategy
val_check_interval: 2000
