_target_: lightning.Trainer
accelerator: "gpu"
callbacks:
  - ${callbacks.best_checkpoint_callback}
  - ${callbacks.last_checkpoint_callback}
  - ${callbacks.exception_checkpoint_callback}
detect_anomaly: false
devices: 1
limit_val_batches: 8
log_every_n_steps: 10
logger: ${logger}
max_epochs: 99999
overfit_batches: 1
precision: bf16-mixed
