train:
  flac: ./data/GigaSpeech/download/extracted/cleaned_flac/splitted/
  hubert: ./data/GigaSpeech/download/extracted/cleaned_flac/hubert_tokens/
  metadata: ./data/GigaSpeech/download/extracted/cleaned_flac/train_metadata.tsv
  root: ./data/GigaSpeech/download/extracted/cleaned_flac/
val:
  flac: ./data/GigaSpeech/download/extracted/cleaned_flac/splitted/
  hubert: ./data/GigaSpeech/download/extracted/cleaned_flac/hubert_tokens/
  metadata: ./data/GigaSpeech/download/extracted/cleaned_flac/val_metadata.tsv
  root: ./data/GigaSpeech/download/extracted/cleaned_flac/
