train:
  audio: ${paths.dataset_root}/audio_pairs/
  metadata: ${paths.dataset_root}/train_files.txt
  tokens: ${paths.dataset_root}/tokens/
  transcript: ${paths.dataset_root}/dialogue_pairs/
val:
  audio: ${paths.dataset_root}/audio_pairs/
  metadata: ${paths.dataset_root}/test_files.txt
  tokens: ${paths.dataset_root}/tokens/
  transcript: ${paths.dataset_root}/dialogue_pairs/
