_target_: speechllm.trainer.Model
gradient_clip_val: 50
lossfuncs: ${losses}
model: ${model}
optimizer_order:
  - default
tokenizer:
  _target_: speechllm.data.utils.get_tokenizer
  model_fpath: ${paths.pretrained_models}/AnyGPT-chat
  offline: ${offline}
train_stage: ${train_stage}
