inference_pipeline:
  - fn: inference
    module: anygpt
modules:
  anygpt:
    _target_: speechllm.models.modules.anygpt.constructor
param_group:
  default:
    - anygpt
pipelines:
  default:
    default:
      - fn: forward
        module: anygpt
