batch_size: 1
data_module:
  _target_: speechllm.data.pipeline.DataModule
  train_dataloader_args:
    batch_size: ${data_module.batch_size}
    collate_fn:
      _partial_: true
      _target_: speechllm.data.collate.collate
      tokenizer:
        _target_: speechllm.data.utils.get_tokenizer
        model_fpath: ${paths.pretrained_models}/AnyGPT-chat
        offline: ${offline}
    drop_last: true
    num_workers: ${data_module.num_workers}
    persistent_workers: ${data_module.persistent_workers}
    pin_memory: ${data_module.pin_memory}
    prefetch_factor: ${data_module.prefetch_factor}
    shuffle: true
  train_dataset: ${data_module.train_dataset}
  val_dataloader_args:
    batch_size: ${data_module.batch_size}
    collate_fn:
      _partial_: true
      _target_: speechllm.data.collate.collate
      tokenizer:
        _target_: speechllm.data.utils.get_tokenizer
        model_fpath: ${paths.pretrained_models}/AnyGPT-chat
        offline: ${offline}
    drop_last: true
    num_workers: 1
    persistent_workers: ${data_module.persistent_workers}
    pin_memory: ${data_module.pin_memory}
    prefetch_factor: 2
    shuffle: true
  val_dataset: ${data_module.val_dataset}
num_preprocess_workers: 16
num_workers: 4
persistent_workers: false
pin_memory: false
prefetch_factor: 2
train_dataset:
  _target_: speechllm.data.pipeline.hf_asr_tts_cot_pipeline
  cache_dir: ${paths.dataset_cache}
  database: ${database.train}
  num_workers: ${data_module.num_preprocess_workers}
  stage: train
val_dataset:
  _target_: speechllm.data.pipeline.hf_asr_tts_cot_pipeline
  cache_dir: ${paths.dataset_cache}
  database: ${database.val}
  num_workers: ${data_module.num_preprocess_workers}
  stage: val
