batch_size: 2
data_module:
  _target_: speechllm.data.pipeline.DataModule
  train_dataloader_args:
    batch_size: ${data_module.batch_size}
    collate_fn:
      _partial_: true
      _target_: speechllm.data.collate.collate
      tokenizer:
        _target_: speechllm.data.utils.get_tokenizer
    drop_last: true
    num_workers: ${data_module.num_workers}
    shuffle: true
  train_dataset: ${data_module.train_dataset}
  val_dataloader_args:
    batch_size: ${data_module.batch_size}
    collate_fn:
      _partial_: true
      _target_: speechllm.data.collate.collate
      tokenizer:
        _target_: speechllm.data.utils.get_tokenizer
    drop_last: true
    num_workers: ${data_module.num_workers}
    shuffle: true
  val_dataset: ${data_module.val_dataset}
num_workers: 16
train_dataset:
  _target_: speechllm.data.pipeline.hf_pipeline
  cache_dir: /data3/robinysh/cache/huggingface/
  database: ${database.train}
  num_workers: ${data_module.num_workers}
  stage: train
val_dataset:
  _target_: speechllm.data.pipeline.hf_pipeline
  cache_dir: /data3/robinysh/cache/huggingface/
  database: ${database.val}
  num_workers: ${data_module.num_workers}
  stage: val
