checkpoint: /storage/${oc.env:USER}/ml/${project_name}/${run_name}
dataset_cache: /storage/${oc.env:USER}/cache/huggingface
gigaspeech_root: /storage/${oc.env:USER}/GigaSpeech
pretrained_models: null
soda_root: /storage/${oc.env:USER}/soda
