checkpoint: /scratch-1/${oc.env:USER}/ml/${project_name}/${run_name}
dataset_cache: /scratch-1/${oc.env:USER}/cache/huggingface
dataset_root: /scratch-1/${oc.env:USER}/GigaSpeech
pretrained_models: /scratch-1/${oc.env:USER}/models
