checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: /data/robin/ml/${project_name}/${run_name}/
  every_n_train_steps: 1000
  mode: min
  monitor: valid/loss
  save_last: true
  save_on_train_epoch_end: true
  save_top_k: 3
  verbose: true
lr_callback:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  log_momentum: true
  logging_interval: step
