best_checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint}/best
  every_n_train_steps: 1000
  mode: min
  monitor: valid/loss
  save_last: true
  save_on_train_epoch_end: true
  save_top_k: 3
  verbose: true
exception_checkpoint_callback:
  _target_: lightning.pytorch.callbacks.OnExceptionCheckpoint
  dirpath: ${paths.checkpoint}
last_checkpoint_callback:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint}/last
  every_n_train_steps: 1000
  mode: max
  monitor: trainer/global_step
  save_top_k: 3
  verbose: true
lr_callback:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  log_momentum: true
  logging_interval: step
