config_optimizers:
  default:
    decay_step: 105000
    learning_rate: 0.0001
    warmup_step: 2000
    weight_decay: 0
defaults:
  - database: default
  - data_module: default
  - model: anygpt
  - losses: default
  - callbacks: default
  - trainer: default
  - lightning_module: default
  - logger: default
last_ckpt: null
load_optimizer: false
project_name: speechllm
train_stage: default
