loss_functions:
  anygpt_loss:
    loss_fn:
      _partial_: true
      _target_: speechllm.losses.anygpt_loss
    scale: 1
loss_sets:
  default:
    default:
      - anygpt_loss
    val:
      - anygpt_loss
